### ISSUE TITLE
Stop syncing gcr.io/cloud-solutions-images and remove from dockerhub

### ISSUE THREAD

**Issue by nielm** [Doublemine/gcr.io-mirror#2]
Please can you stop the syncing from gcr.io/cloud-solutions-images and remove the synced images from dockerhub. 

This repository is obsolete, as it had not been updated for many years. The images within have many high and critical severity vulnerabilities.

Any code that used images from these repositories should be re-written to recompile from source, or use official registry locations,

**Comment by Doublemine** [comment]
Thanks for the heads up; this project needs to be refactored to use the gtihub action for synchronization, and I don't have enough time to deal with it right now, so for now I'll remove it from the readme.
